---recurse=yes
--fields=+nKSa
--extras=+q
--tag-relative=yes
--sort=yes
--exclude=.git
--exclude=build
--exclude=vendor
--exclude=node_modules
-recurse=yes
--fields=+nKSa
--extras=+q
--tag-relative=yes
--sort=yes
--exclude=.git
--exclude=build
--exclude=vendor
--exclude=node_modules
--c-kinds=+p
--c++-kinds=+p
