[window]
opacity = 1.0
dynamic_padding = true
option_as_alt = "OnlyRight"
blur = false

[window.padding]
x = 10
y = 10

[terminal]
shell = "/usr/bin/zsh"

[font]
size = 11.0

[font.normal]
family = "ComicMono"
style = "Regular"

[font.bold]
family = "ComicMono"
style = "Bold"

[font.italic]
family = "ComicMono"
style = "Italic"

[font.bold_italic]
family = "ComicMono"
style = "Bold Italic"

[font.offset]
x = 0
y = 1

[cursor]
style = { shape = "Block", blinking = "Never" }
thickness = 0.2
unfocused_hollow = true
vi_mode_style = { shape = "Block", blinking = "Never" }

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#0D1117"
foreground = "#C4A882"

[colors.cursor]
text = "#0D1117"
cursor = "#F0A030"

[colors.vi_mode_cursor]
text = "#0D1117"
cursor = "#C04018"

[colors.selection]
text = "#C4A882"
background = "#1F1610"

[colors.normal]
black = "#1A1208"
red = "#DC4A20"
green = "#D4A030"
yellow = "#D48B30"
blue = "#B87040"
magenta = "#C05020"
cyan = "#B86030"
white = "#C4A882"

[colors.bright]
black = "#3D2B1A"
red = "#DC4A20"
green = "#D4A030"
yellow = "#D48B30"
blue = "#B87040"
magenta = "#C05020"
cyan = "#C84820"
white = "#DCA880"

[scrolling]
history = 20000
multiplier = 3

[mouse]
hide_when_typing = true

[debug]
render_timer = false

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
