[window]
opacity = 1.0
dynamic_padding = true
option_as_alt = "OnlyRight"
blur = false

[window.padding]
x = 10
y = 10

[terminal]
shell = "/usr/bin/zsh"

[font]
size = 7.0

[font.normal]
family = "Jetbrains Mono Nerd Font"
style = "Regular"

[font.bold]
family = "Jetbrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "Jetbrains Mono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Jetbrains Mono Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 1

[cursor]
style = { shape = "Block", blinking = "Never" }
thickness = 0.2
unfocused_hollow = true
vi_mode_style = { shape = "Block", blinking = "Never" }

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#072626"
foreground = "#A08563"

[colors.cursor]
text = "#072626"
cursor = "#FFD700"

[colors.vi_mode_cursor]
text = "#072626"
cursor = "#FF4500"

[colors.selection]
text = "#A08563"
background = "#0A3B3B"

[colors.normal]
black = "#1A1A1A"
red = "#FF6347"
green = "#32CD32"
yellow = "#DAA520"
blue = "#20B2AA"
magenta = "#FF1493"
cyan = "#00CED1"
white = "#B0B0B0"

[colors.bright]
black = "#303030"
red = "#FF6347"
green = "#32CD32"
yellow = "#FFD700"
blue = "#20B2AA"
magenta = "#FF1493"
cyan = "#00CED1"
white = "#D3D3D3"

[scrolling]
history = 20000
multiplier = 3

[mouse]
hide_when_typing = true

[debug]
render_timer = false
