github.com:
    git_protocol: https
    users:
        nasrlol:
            oauth_token: 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
    user: nasrlol
    oauth_token: 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
