filetype plugin indent on

set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8
set nocompatible
set hidden

set backspace=indent,eol,start
set virtualedit=all

set lazyredraw
set updatetime=250
set ttimeoutlen=10
set timeoutlen=300
set redrawtime=1500

let mapleader = " "
let maplocalleader = " "

syntax enable

set number
set norelativenumber

set showtabline=0
set laststatus=0
set signcolumn=no
set fillchars+=eob:\ 

set guicursor=n-v-c:block-blinkwait300-blinkon200-blinkoff150

set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set autoindent

set ruler
set title
set titlestring=%F

set termguicolors
set background=dark
set ignorecase
set smartcase
set incsearch

set nowrap
set linebreak
set breakindent
set scrolloff=8
set sidescrolloff=8
set splitright
set splitbelow

set cindent
set cinoptions=l1,g0,t0,(0,ws1,N-s,j1
set copyindent
set preserveindent
set backspace=indent,eol,start

set formatoptions-=c
set formatoptions-=r
set formatoptions-=o

set cinwords+=Assert,PushStruct,internal,arena,Arena

set autoread
set autowrite
set nobackup
set noswapfile
set noundofile

set tags=./tags;,tags;

set mouse=
set clipboard=unnamedplus
set completeopt=menu,menuone,noselect
set shortmess+=c
set iskeyword-=_

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

nnoremap <M-Up> :resize +2<CR>
nnoremap <M-Down> :resize -2<CR>
nnoremap <M-Left> :vertical resize -2<CR>
nnoremap <M-Right> :vertical resize +2<CR>

nnoremap <leader>v :vsplit<CR>
nnoremap <leader>h :split<CR>
nnoremap <leader>to :tabnew<CR>
nnoremap <leader>tc :tabclose<CR>
nnoremap <leader>tl :tabnext<CR>
nnoremap <leader>th :tabprevious<CR>

vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

vnoremap < <gv
vnoremap > >gv

nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz
nnoremap n nzz
nnoremap N Nzz

nnoremap <leader>p "_dP
xnoremap <leader>p "_dP

nnoremap <leader>R :%s/\v
vnoremap <leader>R :s/\v

nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>Q :qa!<CR>
nnoremap <C-x><C-f> :Oil<CR>

nnoremap <leader>bn :bnext<CR>
nnoremap <leader>bp :bprevious<CR>
nnoremap <leader>bd :bdelete!<CR>
nnoremap <leader>ba :%bd<bar>e#<bar>bd#<CR>

nnoremap <leader>tr :set invrelativenumber<CR>
nnoremap <leader>tw :set invwrap<CR>
nnoremap <leader>yp :let @+ = expand('%:p')<CR>:echo 'Copied: ' . expand('%:p')<CR>
nnoremap <silent> <leader>sh :terminal<CR>
nnoremap <C-]> g<C-]>

nnoremap <leader><leader> :Files<CR>
nnoremap <leader>fa :Rg<CR>
nnoremap <leader>fb :Buffers<CR>
nnoremap <leader>fr :History<CR>
nnoremap <leader>gs :GFiles?<CR>
nnoremap <leader>sr :History:<CR>
nnoremap <leader>tg :Tags<CR>

if has('nvim')
else
  nnoremap <C-x><C-f> :Explore<CR>
endif

" Disable blinking cursor
set gcr=a:blinkon0

if !exists('g:loaded_matchit')
  runtime macros/matchit.vim
endif

augroup VimGroup
  autocmd!
  autocmd VimLeave * if filereadable('Session.vim') | call writefile(readfile('Session.vim'), 'Session.vim') | endif
augroup END

