monitor = ,preferred,auto,1

$terminal   = alacritty
$menu       = wofi --show drun
$editor     = neovide
$browser    = Mozilla Firefox
$coder      = coder

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = waybar

env = XCURSOR_SIZE,15
env = HYPRCURSOR_SIZE,8
env = HYPRLAND_NO_SD_NOTIFY,1

general {
    gaps_in = 5
    gaps_out = 5
    border_size = 1
    col.active_border = rgba(333333ff)
    col.inactive_border = rgba(444444ff)
    resize_on_border = false
    allow_tearing = true
    layout = scroll
}

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = true
    }

    blur {
        enabled = false
    }
}

animations {
    enabled = true
}

master {
    new_status = master
    mfact = 0.55
    allow_small_split = false
    new_on_top = true
}

misc {
    disable_hyprland_logo = true
    force_default_wallpaper = -1
    vrr = 0
    mouse_move_focuses_monitor = true
    disable_splash_rendering = true
}

render {
    direct_scanout = false
}

input {
    kb_layout = us
    kb_options = altwin:alt_super_win,caps:escape,lv3:ralt_switch
    repeat_rate = 50
    repeat_delay = 140
    follow_mouse = 0
    sensitivity = 0

    touchpad {
        natural_scroll = true
        tap-to-click = false
        drag_lock = false
    }
}

$mainMod = SUPER

bind = $mainMod,Return,exec,$terminal
bind = $mainMod,N,exec,$editor
bind = $mainMod,E,exec,emacs
bind = $mainMod,P,exec,$menu
bind = $mainMod,C,exec,$coder

bind = $mainMod,Q,killactive
bind = $mainMod Shift,Q,exit
bind = $mainMod,V,togglefloating
bind = $mainMod,T,pseudo
# bind = $mainMod,Space,togglesplit
bind = $mainMod,F,fullscreen,0
bind = $mainMod Shift,F,fullscreen,1

bind = $mainMod,left,movefocus,l
bind = $mainMod,right,movefocus,r
bind = $mainMod,up,movefocus,u
bind = $mainMod,down,movefocus,d
bind = $mainMod,h,movefocus,l
bind = $mainMod,j,movefocus,d
bind = $mainMod,k,movefocus,u
bind = $mainMod,l,movefocus,r

bind = $mainMod Ctrl,left,movewindow,l
bind = $mainMod Ctrl,right,movewindow,r
bind = $mainMod Ctrl,up,movewindow,u
bind = $mainMod Ctrl,down,movewindow,d

bind = $mainMod Shift,left,resizeactive,-40 0
bind = $mainMod Shift,right,resizeactive,40 0
bind = $mainMod Shift,up,resizeactive,0 -40
bind = $mainMod Shift,down,resizeactive,0 40

bind = $mainMod,plus,exec,hyprctl keyword master:mfact +0.05
bind = $mainMod,minus,exec,hyprctl keyword master:mfact -0.05

bind = $mainMod,1,workspace,1
bind = $mainMod,2,workspace,2
bind = $mainMod,3,workspace,3
bind = $mainMod,4,workspace,4
bind = $mainMod,5,workspace,5
bind = $mainMod,6,workspace,6
bind = $mainMod,7,workspace,7
bind = $mainMod,8,workspace,8
bind = $mainMod,9,workspace,9
bind = $mainMod,0,workspace,10

bind = $mainMod Shift,1,movetoworkspace,1
bind = $mainMod Shift,2,movetoworkspace,2
bind = $mainMod Shift,3,movetoworkspace,3
bind = $mainMod Shift,4,movetoworkspace,4
bind = $mainMod Shift,5,movetoworkspace,5
bind = $mainMod Shift,6,movetoworkspace,6
bind = $mainMod Shift,7,movetoworkspace,7
bind = $mainMod Shift,8,movetoworkspace,8
bind = $mainMod Shift,9,movetoworkspace,9
bind = $mainMod Shift,0,movetoworkspace,10

bind = $mainMod,S,togglespecialworkspace,magic
bind = $mainMod Shift,S,movetoworkspace,special:magic

bind = $mainMod,mouse_down,workspace,e+1
bind = $mainMod,mouse_up,workspace,e-1

bindm = $mainMod,mouse:272,movewindow
bindm = $mainMod,mouse:273,resizewindow

bindel = ,XF86AudioRaiseVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute,exec,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86MonBrightnessUp,exec,brightnessctl s 10%+
bindel = ,XF86MonBrightnessDown,exec,brightnessctl s 10%-

bind = $mainMod,D,exec,wofi --show run -i
