fork = true
vsync = false
multigrid = true
maximized = false

remember_window_size        = true
remember_window_position    = true


# Padding
padding_top     = 0
padding_bottom  = 0
padding_left    = 0
padding_right   = 0
