set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g default-shell /usr/bin/zsh
set -g history-limit 20000
set -g base-index 1
setw -g pane-base-index 1
set -g mode-keys vi
set -g status-keys vi
set -g renumber-windows on
set -g detach-on-destroy off
set -g mouse off
set -s escape-time 0
set -g display-time 4000
set -g focus-events on
setw -g aggressive-resize on
set -g main-pane-width 110
set -g set-clipboard on

unbind C-b
set -g prefix M-a
bind M-a send-prefix

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-$ split-window -h
bind -n M-% split-window -v
bind -n M-c new-window
bind -n M-z resize-pane -Z

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6

# Split in current directory
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X begin-selection \; send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xsel --clipboard"
bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel "xsel --clipboard"

bind < resize-pane -L 10
bind > resize-pane -R 10
bind + resize-pane -D 10
bind - resize-pane -U 10

set -g status on
set -g status-interval 1
set -g status-position top
set -g status-justify left

set -g status-style bg=default,fg=white
set -g status-left '#[fg=green]#S '
set -g status-right '#[fg=green]%d.%m. %H:%M'
set -g status-left-length 15
set -g status-right-length 15

set -g window-status-format "#I:#W"
set -g window-status-current-format "#[fg=green](#I:#W)"
set -g window-status-separator " "

set -g status-justify centre

# Pane borders
set -g pane-border-status off
set -g pane-border-style fg=colour238,bg=#101010
set -g pane-active-border-style fg=colour113,bg=#151515

bind -n F11 previous-window
bind -n F12 next-window
bind m choose-tree
bind k choose-session

bind -n C-S-Left swap-window -d -t -1
bind -n C-S-Right swap-window -d -t +1

unbind S
bind S command-prompt 'rename-session %%'
bind N new-session
bind B command-prompt -p "New session name:" \
  "new-session -d -s '%%'; move-window -t '%%:'; switch-client -t '%%'"

bind M-s set-window-option synchronize-panes
unbind r
bind r source-file ~/.config/tmux/tmux.conf

bind C-j display-popup -h 20% -w 20% -E "tmux-session-switcher"
bind C-o display-popup -E "tmux-zoxide-window"
bind C-t display-popup -E "tmux-bro"

bind C-f display-popup -h 60% -w 60% -E "tmux-file-picker"
bind C-r display-popup -h 60% -w 60% -E "tmux-file-picker -d"
bind C-g display-popup -h 60% -w 60% -E "tmux-file-picker -g"
bind C-d display-popup -h 60% -w 60% -E "tmux-file-picker --zoxide --dir-only"
bind C-z display-popup -h 60% -w 60% -E "tmux-file-picker --zoxide"

bind C-p display-popup -h 70% -w 70% -E "tmux-snaglord"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-logging'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
