setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT
setopt EXTENDED_GLOB
setopt HIST_REDUCE_BLANKS
setopt SHARE_HISTORY
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt PROMPT_SUBST

bindkey -v
bindkey '^R' history-incremental-search-backward
bindkey '^F' autosuggest-accept
bindkey '^E' edit-command-line

autoload -Uz edit-command-line
autoload -Uz compinit
autoload -Uz vcs_info

zle -N edit-command-line

alias vim="nvim"
alias ll="ls -hal"
alias checkpoint="git add . && git commit -m 'checkpoint' && git push"
alias attach="tmux attach-session -t"
alias new="tmux new-session -s"
alias list="tmux list-sessions"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

memory() {
    while true
    do
        grep -E "VmRSS|VmSize|VmPeak" /proc/70409/status
        sleep 1
    done
}



PROMPT='%n :: '

