;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-insert
	evil-next-line
	evil-normal-state
	evil-previous-line
	project-compile
	))

(setq mc/cmds-to-run-once
      '(
	evil-ret
	))
